---
- hosts: all
  become: true

- name: install first playbook 
  import_playbook: template.yml
  vars: 
    app_user: "administrator"
    http_host: "muhammad"
    http_conf: "muhammad.conf"
    http_port: "80"
    disable_default: true

- name: install second playbook
  import_playbook: template.yml
  vars:
    app_user: "administrator"
    http_host: "abdelhay"
    http_conf: "abdelhay.conf"
    http_port: "80"
    disable_default: true
